import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:tts_flutter_test/speech_synthesis/domain/entities/speech_request_model.dart';
import 'package:tts_flutter_test/speech_synthesis/domain/entities/tts_service_model.dart';

part 'speech_request_dto.freezed.dart';
part 'speech_request_dto.g.dart';

/// Data Transfer Object (DTO) for speech synthesis request
/// 
/// ## What is a DTO?
/// A Data Transfer Object (DTO) is a design pattern used to transfer data between different
/// layers of an application, particularly between the Domain layer and Data layer. Unlike domain
/// entities (models), DTOs are simple data containers without business logic or validation.
/// 
/// ## Why DTOs exist:
/// 1. **Serialization**: DTOs use primitive types (String, int, bool) instead of value objects,
///    making them easy to serialize to/from JSON for API communication
/// 2. **Layer Separation**: They provide a boundary between domain models (which contain business
///    logic) and data structures used for external communication
/// 3. **Framework Independence**: DTOs can be easily converted to JSON for HTTP requests, database
///    storage, or platform channel communication
/// 
/// ## Key Differences from Domain Models:
/// - **Domain Models** (SpeechRequestModel): Use value objects (TextVO, VoiceVO, etc.) for type
///   safety and validation. They represent business concepts.
/// - **DTOs** (SpeechRequestDto): Use primitive types (String, int) for easy serialization.
///   They represent data structures for communication.
/// 
/// ## Freezed Package:
/// The `@freezed` annotation and `freezed_annotation` package generate:
/// - Immutable classes (all fields are final)
/// - `copyWith` method for creating modified copies
/// - `==` operator and `hashCode` for value equality
/// - `toString` method for debugging
/// 
/// ## JSON Serialization:
/// The `json_serializable` package (via `.g.dart` file) generates:
/// - `fromJson` factory constructor to deserialize JSON
/// - `toJson` method to serialize to JSON
/// 
/// This is part of the Data layer in clean architecture.
@freezed
class SpeechRequestDto with _$SpeechRequestDto {
  /// Factory constructor for creating a SpeechRequestDto instance
  /// 
  /// All fields use primitive types (String) instead of value objects to enable
  /// easy JSON serialization for API communication.
  const factory SpeechRequestDto({
    /// The text content to be converted to speech
    /// This is a plain String, unlike the domain model which uses TextVO (a value object)
    required String text,
    
    /// The TTS service to use: 'gemini', 'openai', or 'polly'
    /// This is a String identifier, unlike the domain model which uses TTSServiceModel
    required String service,
    
    /// Optional voice identifier for the TTS service
    /// Different services support different voices (e.g., 'en-US-Standard-A' for Google)
    String? voice,
    
    /// Optional language code in ISO 639-1 format (e.g., 'en', 'es', 'fr')
    /// This determines the language/accent of the generated speech
    String? language,
    
    /// Audio format for the output (default: 'mp3')
    /// Supported formats: 'mp3', 'wav', 'ogg', etc.
    /// Uses @Default annotation from Freezed to provide a default value
    @Default('mp3') String audioFormat,
    
    /// Optional speed parameter for OpenAI TTS (default: 1.0)
    /// Speed range: 0.25 to 4.0
    /// Only used by OpenAI TTS service
    @Default(1.0) double speed,
    
    /// Optional instructions/prompt parameter for TTS services
    /// - OpenAI: Provides guidance on how to speak the text (instructions)
    /// - Gemini: Provides tone and speaking style guidance (prompt)
    /// Example for Gemini: "Say the following in an elated way"
    String? instructions,
  }) = _SpeechRequestDto;
  
  /// Factory constructor to deserialize from JSON
  /// 
  /// This method is generated by `json_serializable` package (in `.g.dart` file).
  /// It converts a `Map<String, dynamic>` (JSON) into a SpeechRequestDto instance.
  /// 
  /// Usage:
  /// ```dart
  /// final json = {'text': 'Hello', 'service': 'gemini', 'audioFormat': 'mp3'};
  /// final dto = SpeechRequestDto.fromJson(json);
  /// ```
  factory SpeechRequestDto.fromJson(Map<String, dynamic> json) =>
      _$SpeechRequestDtoFromJson(json);
  
  /// Factory constructor to convert from domain model to DTO
  /// 
  /// This method bridges the Domain layer and Data layer by converting a domain entity
  /// (SpeechRequestModel) to a DTO. It extracts primitive values from value objects.
  /// 
  /// **Conversion Process:**
  /// 1. Extracts `text.value` from TextVO → String
  /// 2. Extracts `service.value` from TTSServiceModel → String
  /// 3. Extracts `voice?.value` from VoiceVO? → String?
  /// 4. Extracts `language?.value` from LanguageVO? → String?
  /// 5. Extracts `audioFormat?.value` from AudioFormatVO? → String
  /// 
  /// This conversion is necessary because:
  /// - Domain models use value objects for type safety and validation
  /// - DTOs use primitive types for serialization and external communication
  /// 
  /// Usage:
  /// ```dart
  /// final domainModel = SpeechRequestModel(...);
  /// final dto = SpeechRequestDto.fromDomain(domainModel);
  /// final json = dto.toJson(); // Now ready for API call
  /// ```
  factory SpeechRequestDto.fromDomain(SpeechRequestModel model) {
    // Access the underlying value from the service value object
    // The .value property extracts the primitive String from TTSServiceModel
    final serviceValue = model.service.value;
    
    return SpeechRequestDto(
      // Extract primitive String from TextVO value object
      text: model.text.value,
      
      // Extract primitive String from TTSServiceModel value object
      service: serviceValue,
      
      // Extract optional String from VoiceVO value object (if present)
      voice: model.voice?.value,
      
      // Extract optional String from LanguageVO value object (if present)
      language: model.language?.value,
      
      // Extract String from AudioFormatVO, defaulting to 'mp3' if null
      audioFormat: model.audioFormat?.value ?? 'mp3',
      
      // Speed and instructions are not in domain model yet, use defaults
      // These are OpenAI-specific parameters
      speed: 1.0, // Default speed
      instructions: null, // No instructions by default
    );
  }
}

