// Mocks generated by Mockito 5.4.6 from annotations
// in tts_flutter_test/test/speech_synthesis/domain/use_cases/convert_text_to_speech_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:result_type/result_type.dart' as _i4;
import 'package:tts_flutter_test/speech_synthesis/domain/entities/speech_request_model.dart'
    as _i7;
import 'package:tts_flutter_test/speech_synthesis/domain/entities/speech_response_model.dart'
    as _i5;
import 'package:tts_flutter_test/speech_synthesis/domain/errors/speech_synthesis_error.dart'
    as _i6;
import 'package:tts_flutter_test/speech_synthesis/domain/repositories/i_speech_synthesis_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ISpeechSynthesisRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISpeechSynthesisRepository extends _i1.Mock
    implements _i2.ISpeechSynthesisRepository {
  MockISpeechSynthesisRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.SpeechResponseModel, _i6.SpeechSynthesisError>>
  convertTextToSpeech(
    _i7.SpeechRequestModel request, {
    double? speed,
    String? instructions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #convertTextToSpeech,
              [request],
              {#speed: speed, #instructions: instructions},
            ),
            returnValue:
                _i3.Future<
                  _i4.Result<_i5.SpeechResponseModel, _i6.SpeechSynthesisError>
                >.value(
                  _i8.dummyValue<
                    _i4.Result<
                      _i5.SpeechResponseModel,
                      _i6.SpeechSynthesisError
                    >
                  >(
                    this,
                    Invocation.method(
                      #convertTextToSpeech,
                      [request],
                      {#speed: speed, #instructions: instructions},
                    ),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Result<_i5.SpeechResponseModel, _i6.SpeechSynthesisError>
          >);
}
